#' convert csv to xpt and sas7bdat (Windows-only)
#'
#' convert csv to xpt and sas7bdat by  sas script file convert_csv2sas.sas which can be run inside sas to make genuine xpt and sas7bdat files generated by sas software
#'
#' @param wd working directory containing csv files
#' @param xpt directory of xpt files
#' @param sas7bdat directory of sas7bdat files
#' @param output sas file output
#' @param openfile if TRUE, output file will be opened
#'
#' @export
#' @return sas file which can be run inside sas to make genuine xpt and sas7bdat files generated by sas software
#' @examples
#' \donttest{
#'   write.csv(Theoph, 'Theoph.csv', row.names = FALSE)
#'   write.csv(Indometh, 'Indometh.csv', row.names = FALSE)
#'   csv2sas()  # Means "Current directory"
#' }

csv2sas <- function(wd = getwd(), xptPath = getwd(), sas7bdatPath = getwd(), output = "csv2sas.sas", openfile = FALSE){
  ##### MAKING "CSV2XPT.SAS"

  glob2rx("*.CSV")
  glob2rx("*.csv")
  # dir(patten=glob2rx("*.csv"))
  # lstR = dir(pattern="^.*\\.[rR]$")
  # dir(pattern="^.*\\.(CSV|csv)$")
  # dir(pattern="^.*\\.(C|c)(S|s)(V|v)$")

  CSVfolder = wd
  #setwd(CSVfolder)
  CSVs = dir(pattern="^.*\\.[cC][sS][vV]$")
  nCSV = length(CSVs)

  SASscript = vector()
  for (i in 1:nCSV) {
    tData = read.csv(CSVs[i], as.is=TRUE)
    ColNames = colnames(tData)
    nCol = length(ColNames)
    VarString = "  INPUT"
    for (j in 1:nCol) {
      Width = max(nchar(tData[, ColNames[j]]), na.rm=TRUE)
      if (Width == -Inf | Width == 0) Width = 1 # !!! Minimum width is 1.
      VarString = paste0(VarString, " ", ColNames[j], " :$", Width,".") # !!! informat should be like :$w. for .CSV file
    }
    VarString = paste0(VarString, ";")

    Name = strsplit(CSVs[i], "\\.[cC][sS][vV]")[[1]]
    if (nchar(Name) > 8) Name = substr(Name, 1, 8)  # !!! Member name in XPT file is restricted. The length is preferebly 8 or less.
    SASscript = c(SASscript, paste0("DATA WORK.", Name, ";"))
    SASscript = c(SASscript, paste0("  INFILE '", CSVfolder, "/", CSVs[i],"' DLM=',' FIRSTOBS=2 MISSOVER DSD LRECL=32767;"))
    SASscript = c(SASscript, VarString)
    SASscript = c(SASscript, "RUN;")
    SASscript = c(SASscript, "")
    #SASscript = c(SASscript, paste0("LIBNAME T", i, " XPORT '..\\data-xpt\\", Name, ".xpt';"))
    SASscript = c(SASscript, paste0("LIBNAME T", i, " XPORT '",  normalizePath(xptPath), "\\", Name, ".xpt';"))
    SASscript = c(SASscript, paste0("PROC COPY IN=WORK OUT=T", i, "; SELECT ", Name, "; RUN;"))
    SASscript = c(SASscript, sprintf("LIBNAME OUT '%s';", normalizePath(sas7bdatPath)))
    SASscript = c(SASscript, sprintf("DATA OUT.%s;", Name))
    SASscript = c(SASscript, sprintf("  SET WORK.%s;", Name))
    SASscript = c(SASscript, "Run;")
    SASscript = c(SASscript, "")
    SASscript = c(SASscript, "")
  }
  writeLines(SASscript, output)
  if (openfile) {
    browseURL(output)
    print(sprintf('%s/%s was generated and output file will be opened soon.', wd, output))
  } else {
    print(sprintf('%s/%s was generated.', wd, output))
  }
}
